/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Push notification handler - THIS IS THE KEY for iOS to show notifications
self.addEventListener('push', (event) => {
  console.log('[SW] Push event received:', event);

  if (!event.data) {
    console.log('[SW] Push event but no data');
    return;
  }

  let data: { title?: string; body?: string; data?: { url?: string } };
  
  try {
    data = event.data.json();
    console.log('[SW] Push data parsed:', data);
  } catch (e) {
    // Fallback if not JSON
    data = {
      title: 'Clarita la cuenta',
      body: event.data.text(),
    };
    console.log('[SW] Push data as text:', data);
  }

  const title = data.title || 'Clarita la cuenta';
  const options: NotificationOptions & { renotify?: boolean } = {
    body: data.body || '',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    tag: 'clarita-notification',
    data: {
      url: data.data?.url || '/',
    },
  };

  // @ts-ignore - renotify is a valid option but not in TS types
  options.renotify = true;

  console.log('[SW] Showing notification:', title, options);

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification clicked:', event);
  
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Try to focus an existing window
      for (const client of clientList) {
        if ('focus' in client) {
          client.focus();
          if ('navigate' in client) {
            (client as WindowClient).navigate(urlToOpen);
          }
          return;
        }
      }
      // Open a new window if none exists
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Activate immediately
self.addEventListener('activate', (event) => {
  console.log('[SW] Activate event');
  event.waitUntil(self.clients.claim());
});

self.addEventListener('install', (event) => {
  console.log('[SW] Install event');
  self.skipWaiting();
});
